import { Product } from "../domain";

/**
 * Production-quality seed data - NOT fake financial data, but product catalog.
 * All financial numbers (orders) are derived from real user actions.
 */
export const seedProducts: Product[] = [
  {
    id: "prod_001",
    name: "Noir Oud Intense",
    slug: "noir-oud-intense",
    description:
      "A deep, smoky oud woven with saffron and dark vanilla. For nights that demand presence. Long-lasting, intimate sillage crafted for the modern Indian evening.",
    price: 3499,
    compareAtPrice: 4299,
    sku: "PF-NOIR-50",
    gender: "unisex",
    fragranceFamily: "oud",
    intensity: "intense",
    longevity: "10-12h",
    sillage: "strong",
    occasion: ["evening", "formal"],
    season: ["winter", "autumn"],
    tags: ["oud", "saffron", "vanilla", "signature"],
    status: "published",
    isBestseller: true,
    isNew: false,
    isFeatured: true,
    seoTitle: "Noir Oud Intense — PUREFOME",
    seoDescription: "Smoky oud, saffron, dark vanilla. Intense longevity.",
    canonicalUrl: "/products/noir-oud-intense",
    ogImage: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&q=80",
    createdAt: "2024-01-15T00:00:00.000Z",
    updatedAt: "2024-01-15T00:00:00.000Z",
    variants: [
      { id: "var_001_50", productId: "prod_001", size: "50ml", price: 3499, sku: "PF-NOIR-50", stock: 42 },
      { id: "var_001_100", productId: "prod_001", size: "100ml", price: 5499, sku: "PF-NOIR-100", stock: 18 },
    ],
    images: [
      { id: "img_001_1", productId: "prod_001", url: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&q=80", type: "hero", sortOrder: 0 },
      { id: "img_001_2", productId: "prod_001", url: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80", type: "gallery", sortOrder: 1 },
    ],
    notes: [
      { id: "n001", productId: "prod_001", stage: "top", noteName: "Saffron" },
      { id: "n002", productId: "prod_001", stage: "top", noteName: "Bergamot" },
      { id: "n003", productId: "prod_001", stage: "heart", noteName: "Oud" },
      { id: "n004", productId: "prod_001", stage: "heart", noteName: "Rose" },
      { id: "n005", productId: "prod_001", stage: "base", noteName: "Vanilla" },
      { id: "n006", productId: "prod_001", stage: "base", noteName: "Amber" },
    ],
    totalStock: 60,
  },
  {
    id: "prod_002",
    name: "Citrus Verbena Lumière",
    slug: "citrus-verbena-lumiere",
    description:
      "Sunlit bergamot, verbena and white musk. A fresh, transparent scent for daily wear — crisp as morning air in the hills.",
    price: 2499,
    compareAtPrice: null,
    sku: "PF-CITR-50",
    gender: "unisex",
    fragranceFamily: "fresh",
    intensity: "moderate",
    longevity: "6-8h",
    sillage: "moderate",
    occasion: ["daily", "casual"],
    season: ["summer", "spring"],
    tags: ["citrus", "verbena", "musk", "fresh"],
    status: "published",
    isBestseller: false,
    isNew: true,
    isFeatured: true,
    seoTitle: "Citrus Verbena Lumière — PUREFOME",
    seoDescription: "Bergamot, verbena, white musk. Fresh daily scent.",
    canonicalUrl: "/products/citrus-verbena-lumiere",
    ogImage: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&q=80",
    createdAt: "2024-03-01T00:00:00.000Z",
    updatedAt: "2024-03-01T00:00:00.000Z",
    variants: [
      { id: "var_002_50", productId: "prod_002", size: "50ml", price: 2499, sku: "PF-CITR-50", stock: 55 },
      { id: "var_002_100", productId: "prod_002", size: "100ml", price: 3999, sku: "PF-CITR-100", stock: 30 },
    ],
    images: [
      { id: "img_002_1", productId: "prod_002", url: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&q=80", type: "hero", sortOrder: 0 },
    ],
    notes: [
      { id: "n007", productId: "prod_002", stage: "top", noteName: "Bergamot" },
      { id: "n008", productId: "prod_002", stage: "top", noteName: "Verbena" },
      { id: "n009", productId: "prod_002", stage: "heart", noteName: "Jasmine" },
      { id: "n010", productId: "prod_002", stage: "base", noteName: "White Musk" },
    ],
    totalStock: 85,
  },
  {
    id: "prod_003",
    name: "Velvet Amber Noir",
    slug: "velvet-amber-noir",
    description:
      "Warm amber, tonka and sandalwood — a soft, enveloping trail that lingers. Crafted for intimate evenings and festive gatherings.",
    price: 2999,
    compareAtPrice: 3499,
    sku: "PF-VELV-50",
    gender: "women",
    fragranceFamily: "amber",
    intensity: "strong",
    longevity: "8-10h",
    sillage: "moderate",
    occasion: ["evening", "festive"],
    season: ["winter", "autumn"],
    tags: ["amber", "tonka", "sandalwood"],
    status: "published",
    isBestseller: true,
    isNew: false,
    isFeatured: false,
    seoTitle: "Velvet Amber Noir — PUREFOME",
    seoDescription: "Amber, tonka, sandalwood. Warm festive scent.",
    canonicalUrl: "/products/velvet-amber-noir",
    ogImage: "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=800&q=80",
    createdAt: "2024-02-10T00:00:00.000Z",
    updatedAt: "2024-02-10T00:00:00.000Z",
    variants: [{ id: "var_003_50", productId: "prod_003", size: "50ml", price: 2999, sku: "PF-VELV-50", stock: 22 }],
    images: [
      { id: "img_003_1", productId: "prod_003", url: "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=800&q=80", type: "hero", sortOrder: 0 },
    ],
    notes: [
      { id: "n011", productId: "prod_003", stage: "top", noteName: "Pink Pepper" },
      { id: "n012", productId: "prod_003", stage: "heart", noteName: "Amber" },
      { id: "n013", productId: "prod_003", stage: "base", noteName: "Sandalwood" },
    ],
    totalStock: 22,
  },
  {
    id: "prod_004",
    name: "Midnight Bloom",
    slug: "midnight-bloom",
    description:
      "Tuberose, jasmine and night-blooming florals with a hint of black pepper. Sensual, modern, unforgettable.",
    price: 2799,
    compareAtPrice: null,
    sku: "PF-MIDN-50",
    gender: "women",
    fragranceFamily: "floral",
    intensity: "moderate",
    longevity: "7-9h",
    sillage: "moderate",
    occasion: ["evening", "date"],
    season: ["spring", "summer"],
    tags: ["tuberose", "jasmine", "floral"],
    status: "published",
    isBestseller: false,
    isNew: true,
    isFeatured: true,
    seoTitle: "Midnight Bloom — PUREFOME",
    seoDescription: "Tuberose, jasmine, night florals.",
    canonicalUrl: "/products/midnight-bloom",
    ogImage: "https://images.unsplash.com/photo-1593487568720-7992814d30d3?w=800&q=80",
    createdAt: "2024-03-20T00:00:00.000Z",
    updatedAt: "2024-03-20T00:00:00.000Z",
    variants: [{ id: "var_004_50", productId: "prod_004", size: "50ml", price: 2799, sku: "PF-MIDN-50", stock: 35 }],
    images: [
      { id: "img_004_1", productId: "prod_004", url: "https://images.unsplash.com/photo-1593487568720-7992814d30d3?w=800&q=80", type: "hero", sortOrder: 0 },
    ],
    notes: [
      { id: "n014", productId: "prod_004", stage: "top", noteName: "Black Pepper" },
      { id: "n015", productId: "prod_004", stage: "heart", noteName: "Tuberose" },
      { id: "n016", productId: "prod_004", stage: "base", noteName: "Musk" },
    ],
    totalStock: 35,
  },
  {
    id: "prod_005",
    name: "Oud Imperial",
    slug: "oud-imperial",
    description:
      "Pure aged oud, leather and incense. A statement of quiet luxury. Limited micro-batch.",
    price: 5999,
    compareAtPrice: 6999,
    sku: "PF-OUDI-50",
    gender: "men",
    fragranceFamily: "oud",
    intensity: "intense",
    longevity: "12h+",
    sillage: "strong",
    occasion: ["formal", "evening"],
    season: ["winter"],
    tags: ["oud", "leather", "incense", "limited"],
    status: "published",
    isBestseller: false,
    isNew: false,
    isFeatured: true,
    seoTitle: "Oud Imperial — PUREFOME",
    seoDescription: "Aged oud, leather, incense. Limited.",
    canonicalUrl: "/products/oud-imperial",
    ogImage: "https://images.unsplash.com/photo-1582211594533-268f4a00a8cc?w=800&q=80",
    createdAt: "2023-11-01T00:00:00.000Z",
    updatedAt: "2023-11-01T00:00:00.000Z",
    variants: [{ id: "var_005_50", productId: "prod_005", size: "50ml", price: 5999, sku: "PF-OUDI-50", stock: 8 }],
    images: [
      { id: "img_005_1", productId: "prod_005", url: "https://images.unsplash.com/photo-1582211594533-268f4a00a8cc?w=800&q=80", type: "hero", sortOrder: 0 },
    ],
    notes: [
      { id: "n017", productId: "prod_005", stage: "top", noteName: "Incense" },
      { id: "n018", productId: "prod_005", stage: "heart", noteName: "Oud" },
      { id: "n019", productId: "prod_005", stage: "base", noteName: "Leather" },
    ],
    totalStock: 8,
  },
  {
    id: "prod_006",
    name: "Aqua Neroli",
    slug: "aqua-neroli",
    description:
      "Neroli, sea salt and driftwood. A Mediterranean breeze bottled for humid Indian summers.",
    price: 2299,
    compareAtPrice: null,
    sku: "PF-AQUA-50",
    gender: "unisex",
    fragranceFamily: "aquatic",
    intensity: "light",
    longevity: "5-6h",
    sillage: "soft",
    occasion: ["daily", "casual"],
    season: ["summer"],
    tags: ["neroli", "aquatic", "fresh"],
    status: "published",
    isBestseller: false,
    isNew: false,
    isFeatured: false,
    seoTitle: "Aqua Neroli — PUREFOME",
    seoDescription: "Neroli, sea salt, driftwood. Aquatic fresh.",
    canonicalUrl: "/products/aqua-neroli",
    ogImage: "https://images.unsplash.com/photo-1519669556878-63bdad8a1a49?w=800&q=80",
    createdAt: "2024-02-28T00:00:00.000Z",
    updatedAt: "2024-02-28T00:00:00.000Z",
    variants: [{ id: "var_006_50", productId: "prod_006", size: "50ml", price: 2299, sku: "PF-AQUA-50", stock: 0 }],
    images: [
      { id: "img_006_1", productId: "prod_006", url: "https://images.unsplash.com/photo-1519669556878-63bdad8a1a49?w=800&q=80", type: "hero", sortOrder: 0 },
    ],
    notes: [
      { id: "n020", productId: "prod_006", stage: "top", noteName: "Neroli" },
      { id: "n021", productId: "prod_006", stage: "heart", noteName: "Sea Salt" },
      { id: "n022", productId: "prod_006", stage: "base", noteName: "Driftwood" },
    ],
    totalStock: 0,
  },
  {
    id: "prod_007",
    name: "Spice Souk",
    slug: "spice-souk",
    description:
      "Cardamom, cinnamon and smoked vanilla inspired by the old spice markets. Warm, gourmand, memorable.",
    price: 2699,
    compareAtPrice: null,
    sku: "PF-SPIC-50",
    gender: "unisex",
    fragranceFamily: "spicy",
    intensity: "strong",
    longevity: "8h",
    sillage: "moderate",
    occasion: ["festive", "evening"],
    season: ["winter", "autumn"],
    tags: ["cardamom", "cinnamon", "vanilla"],
    status: "published",
    isBestseller: true,
    isNew: false,
    isFeatured: false,
    seoTitle: "Spice Souk — PUREFOME",
    seoDescription: "Cardamom, cinnamon, smoked vanilla.",
    canonicalUrl: "/products/spice-souk",
    ogImage: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80",
    createdAt: "2024-01-20T00:00:00.000Z",
    updatedAt: "2024-01-20T00:00:00.000Z",
    variants: [{ id: "var_007_50", productId: "prod_007", size: "50ml", price: 2699, sku: "PF-SPIC-50", stock: 40 }],
    images: [
      { id: "img_007_1", productId: "prod_007", url: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80", type: "hero", sortOrder: 0 },
    ],
    notes: [
      { id: "n023", productId: "prod_007", stage: "top", noteName: "Cardamom" },
      { id: "n024", productId: "prod_007", stage: "heart", noteName: "Cinnamon" },
      { id: "n025", productId: "prod_007", stage: "base", noteName: "Vanilla" },
    ],
    totalStock: 40,
  },
  {
    id: "prod_008",
    name: "Rose Éclat",
    slug: "rose-eclat",
    description:
      "Damask rose, peony and soft musk — a luminous floral with a powdery dry-down. Effortlessly romantic.",
    price: 2899,
    compareAtPrice: null,
    sku: "PF-ROSE-50",
    gender: "women",
    fragranceFamily: "floral",
    intensity: "moderate",
    longevity: "7h",
    sillage: "moderate",
    occasion: ["daily", "date"],
    season: ["spring"],
    tags: ["rose", "peony", "musk"],
    status: "published",
    isBestseller: false,
    isNew: true,
    isFeatured: false,
    seoTitle: "Rose Éclat — PUREFOME",
    seoDescription: "Damask rose, peony, musk.",
    canonicalUrl: "/products/rose-eclat",
    ogImage: "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=800&q=80",
    createdAt: "2024-04-10T00:00:00.000Z",
    updatedAt: "2024-04-10T00:00:00.000Z",
    variants: [{ id: "var_008_50", productId: "prod_008", size: "50ml", price: 2899, sku: "PF-ROSE-50", stock: 28 }],
    images: [
      { id: "img_008_1", productId: "prod_008", url: "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=800&q=80", type: "hero", sortOrder: 0 },
    ],
    notes: [
      { id: "n026", productId: "prod_008", stage: "top", noteName: "Damask Rose" },
      { id: "n027", productId: "prod_008", stage: "heart", noteName: "Peony" },
      { id: "n028", productId: "prod_008", stage: "base", noteName: "Musk" },
    ],
    totalStock: 28,
  },
];
